apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "medical-fraud-detector"
  namespace: "medical-fraud-detection"
spec:
  predictor:
    serviceAccountName: medical-fraud-sa
    containers:
      - name: kserve-container
        image: bittush8789/medical-claim-fraud-detection:latest
        ports:
          - containerPort: 5000
            protocol: TCP
        env:
          - name: PORT
            value: "5000"
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
