global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'medical-fraud-detection-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['medical-fraud-detector.medical-fraud-detection.svc.cluster.local:5000']
